### ISSUE TITLE
demo build broken

### ISSUE THREAD

**Issue by 0xAubrey** [williamngan/pts-react-example#1]
demo build at https://williamngan.github.io/pts-react-example/build/ is broken

I think adding this line (or some variant) to your package.json will solve if you're using create-react-app:
`"homepage": "https://williamngan.github.io/pts-react-example"`

**Comment by williamngan** [comment]
Oops, I totally forgot to update this react repo. Sorry about that, I'll try to fix it tomorrow. Thanks for reporting, @0xAubrey !

**Comment by williamngan** [comment]
Actually I just updated the package versions and it seems to be working now. Will take a closer look and update React etc soon.

**Comment by akuji1993** [comment]
The one hosted here still doesn't load.

**Comment by williamngan** [comment]
Oops, sorry, forgot to add "homepage" to package.json. Should be fixed now.

I'll clean this up more this weekend. Also looks like es6 minify will finally work with react-scripts 2.0 next. Stay tuned!

**Comment by williamngan** [comment]
I rewrote the example components and updated the docs. Please take a look and see if you find any issues. Thanks everyone!
https://williamngan.github.io/pts-react-example/build/

**Comment by williamngan** [comment]
Update: `npm run build` now completes without errors, thanks to neutrino.js. See the updated README for more.
